-- 開発環境用: resident_table を新列構成で再作成
DROP TABLE IF EXISTS resident_table;

CREATE TABLE resident_table (
  "宛名番号"                              INTEGER NOT NULL PRIMARY KEY,
  "世帯番号"                              TEXT,
  "住民種別"                              TEXT,
  "住民状態"                              TEXT,
  "住民票コード"                          TEXT,
  "氏名"                                  TEXT,
  "氏_日本人"                             TEXT,
  "名_日本人"                             TEXT,
  "氏名_外国人ローマ字"                   TEXT,
  "氏名_外国人漢字"                       TEXT,
  "氏名_振り仮名（フリガナ）"             TEXT,
  "氏_日本人_振り仮名"                    TEXT,
  "名_日本人_振り仮名"                    TEXT,
  "氏名_氏名のカタカナ表記"               TEXT,
  "性別"                                  TEXT,
  "性別表記"                              TEXT,
  "生年月日_元号"                         TEXT,
  "生年月日"                              TEXT,
  "続柄コード1"                           TEXT,
  "続柄表記"                              TEXT,
  "世帯主氏名"                            TEXT,
  "住所_町字コード"                       TEXT,
  "住所_町字"                             TEXT,
  "住所_番地号表記"                       TEXT,
  "住所_番地枝番数値"                     TEXT,
  "住所_方書"                             TEXT,
  "住所_郵便番号"                         TEXT,
  "住所を定めた年月日"                    TEXT,
  "本籍"                                  TEXT,
  "本籍_地番号または、街区符号"           TEXT,
  "戸籍_筆頭者"                           TEXT,
  "地区管理コード1"                       TEXT,
  "記載順位"                              INTEGER,
  "基礎年金番号"                          TEXT
);
